### ISSUE TITLE
Certificate is Expired

### ISSUE THREAD

**Issue by zengk95** [jfrog/setup-jfrog-cli#133]
### Describe the bug

We're using the jfrog cli setup and getting the following errors when downloading the CLI from the releases page. 

### Current behavior

```
Setup JFrog CLI
  Downloading JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.52.9/jfrog-cli-linux-amd64/jfrog
  certificate has expired
  Waiting [12](REDACTED/actions/runs/7569598/jobs/17729308?pr=6371#step:7:13) seconds before trying again
  certificate has expired
  Waiting 19 seconds before trying again
  Error: certificate has expired
```

### Setup JFrog CLI version

v4

### JFrog CLI version

2.52.9

### Workflow operating system type and version

Linux

**Comment by trdyer** [comment]
I am also seeing this

**Comment by diegotecbr** [comment]
We are experiencing the same problem, @jfrogbot 
 any predictions for a solution?

**Comment by jayantshelkewdc** [comment]
seeing the same issue affecting our CI/CD pipelines. 
When can we expect to have this resolved ?

**Comment by chrisbolt** [comment]
Please use the thumbs up reaction instead of commenting, this is happening for everyone and they just need to renew the certificate.

**Comment by wwsean08** [comment]
A temporary workaround if you were using v3 is to point to my commit that I created which ignores the SSL cert error, be sure to revert when it's fixed.  Here's the compare, https://github.com/jfrog/setup-jfrog-cli/compare/master...wwsean08:setup-jfrog-cli:fix-ssl-error, and if you point to `69b02f2ebc101152b665373aa42c070dfbffe231` it will work, you don't even have to change the repo reference because of how github works.  This was something I implemented for work and we are using actively tonight as a hotfix around this cert issue.

**Comment by wwsean08** [comment]
Or don't use the patch, they deleted all their binaries 🤦🏻 , I've raised up a ticket with enterprise support and gotten people on it.

**Comment by wwsean08** [comment]
It appears the cert is fixed and my patch is no longer needed

**Comment by pedroinacio11** [comment]
It's working again.

**Comment by eyalbe4** [comment]
I'm closing this issue, since it has been resolved, and is being learned internally.

**Comment by wwsean08** [comment]
Hopefully this year the lesson sticks as this happened last year as well ;)
