### ISSUE TITLE
Add option to disable Summary output

### ISSUE THREAD

**Issue by kxc171** [jfrog/setup-jfrog-cli#164]
### Is your feature request related to a problem? Please describe.

The Action is configured to **always** generate a Workflow Summary. This can be problematic when the user wants to create their own Summary as part of a separate process.

### Describe the solution you'd like to see

It would be nice to have the option to **disable** generating a Workflow Summary, so the user can provide their own or none at all.

### Describe alternatives you've considered

There are no alternatives other than configuring the JFrog CLI in your workflow manually.

**Comment by bryancuster** [comment]
It addition to disabling it completely it would be nice to disable each of `Files uploaded to Artifactory by this workflow` and `Build info published to Artifactory by this workflow` independently.

**Comment by picyg-intel** [comment]
We have complex workflow, which has multiple jobs which call setup-jfrog+call cli. 
This feature is spamming our own summary, rendering it useless.
Also, the links in the jfrog summary are invalid (not sure why). 

We all that in mind, having the feature to disable it is very welcomed.

**Comment by EyalDelarea** [comment]
> We have complex workflow, which has multiple jobs which call setup-jfrog+call cli. This feature is spamming our own summary, rendering it useless. Also, the links in the jfrog summary are invalid (not sure why).
> 
> With all that in mind, having the feature to disable it is very welcomed.

Hi @picyg-intel,

Thank you for your feedback!

Regarding the links, they may appear invalid because your `JF_URL` is defined as a secret and thus gets masked by GitHub.

Regarding the spamming issue, we will implement a feature flag to disable the job summary. If you have any other suggestions for improving job summaries in complex workflows like yours, we would appreciate your feedback!

**Comment by picyg-intel** [comment]
Thanks @EyalDelarea ! 

Not sure if this technically possible, but this summary would be quite nice if it appeared once in summary, regardless how many times artifactory upload occurs.

**Comment by jayantshelke-wdc** [comment]
Hi @EyalDelarea , 

Thanks for the maintaining the action. very helpful. 

We have a similar scenario to @picyg-intel , where we execute a matrix job for builds and tests and it ends up showing the JFROG summary for each job for all 150 jobs, thus making it almost not usable. While disabling is one way to alleviate the pain, I think there is good value in the feature and tweaking it to work for CI would be great. With that thought a possible option : 
- Would it be ok to allow an option to output(JSON/markdown) the summary rather than posting it to job summary ? That way the calling workflow can take care of combining the summaries and post just one summary which is all we need as part of the overall CI flow.

PS : I haven't dug into details of the markdown but I am assuming combining the summaries into 1 is not too much of trouble.

**Comment by EyalDelarea** [comment]
Wrapping up this issue as the feature flag is about to be released.

**@bryancuster**: Currently, we do not plan to add such a feature of settings to the job summaries, but you are more than welcome to open a feature request and suggest what will be a convenient way for you to set up those possible settings.

@picyg-intel & @jayantshelke-wdc: Currently, the job summary is limited to individual job scopes. I suggest submitting a feature request to explore combining multiple jobs into a single summary. While feasible, It would require additional configuration and setups from the users (such as another action or workflow) to ensure seamless communication between the jobs, and won't work out of the box like today.

Thank you all for your feedback!
We aim to make the feature the best it can be, and your input truly helps us improve.

Best regards,
Eyal Delarea
