### ISSUE TITLE
Misleading Content in OIDC Example

### ISSUE THREAD

**Issue by tomjfrog** [jfrog/setup-jfrog-cli#171]
### Describe the bug

In the OIDC guidance, there is a section titled "Example step utilizing OpenID Connect".  In the code snippet, the `JF_URL` is a `secret`.  Later in the documentation, it's noted that:

```
The Job Summary UI includes direct links to the JFrog Platform UI. It's important to note that for the platform links to function correctly, JF_URL should be set as a variable rather than a secret. This is to prevent GitHub from masking the URL.
```

Can this be corrected or clarified?

### Current behavior

The documentation is a little confusing as per the Bug description.

### Expected behavior

Consistent approach to using either an `var` or `secrets` in the code examples of setup

### Setup JFrog CLI version

@v4

### JFrog CLI version

@v4

### Workflow operating system type and version

N/A

**Comment by EyalDelarea** [comment]
Hey @tomjfrog,

Thank you for reporting this issue.
We will update the documentation to use vars instead of secrets.

To clarify, until now, we advised our users to define the `JF_URL` as a secret. With the release of JFrog Job Summaries, we have changed our approach to setting the `JF_URL` as a var instead of a secret to prevent GitHub from masking the URL in the summary.

**Comment by tomjfrog** [comment]
Understood, thanks for the improvement @EyalDelarea 🐸
