### ISSUE TITLE
Make `isHeaderPngAccessible()` toggleable for offline environments

### ISSUE THREAD

**Issue by ccano2011** [jfrog/setup-jfrog-cli#226]
### Is your feature request related to a problem? Please describe.

https://github.com/jfrog/setup-jfrog-cli/blob/18e785fb220d332edbf01964f853ff0fcaa22220/src/utils.ts#L743

The new addition is nice, but waiting 2 minutes for it to timeout adds to build times in an offline environment

### Describe the solution you'd like to see

- uses: jfrog/setup-jfrog-cli@v4
  with:
    disable-online-header-summary: true

### Describe alternatives you've considered

Include the header in the binary or remove that online check altogether

**Comment by hazeltonl** [comment]
Maybe even just reduce the timeout?

**Comment by CrafterJSS** [comment]
Replicated the issue:
This is annoying with multiple jobs (potentially in series).
![Image](https://github.com/user-attachments/assets/91a26f36-dd5c-4463-bde4-951bd32e1845)

**Comment by EyalDelarea** [comment]
Hey @ccano2011,

Thank you for submitting this feature request.
I would suggest reducing the timeout and avoiding multiple checks, rather than requiring the user to specify whether there is an internet connection.
I've opened a [PR](https://github.com/jfrog/setup-jfrog-cli/pull/235) to address this.
