### ISSUE TITLE
Github Actions : deprecated env command

### ISSUE THREAD

**Issue by manuchandrasekhar** [jfrog/setup-jfrog-cli#29]
As of Dec 1st, the GitHub actions pipelines using set-env were failing due to the change in the GitHub actions handling the environment vars. 

-  version used:  jfrog/setup-jfrog-cli@v1.0.5

Does the latest version of the jfrog action support environment files or is it still using set-env  ? below are some of the failures noticed with the rt upload.

![Screen Shot 2020-12-03 at 6 26 47 PM](https://user-images.githubusercontent.com/70243489/101100782-1b56ba80-3595-11eb-9846-ed7af65cf1a6.png)
![Screen Shot 2020-12-03 at 6 27 05 PM](https://user-images.githubusercontent.com/70243489/101100799-26114f80-3595-11eb-9cb1-86ee6916c347.png)

**Comment by eyalbe4** [comment]
Thank you for sharing this information @manuchandrasekhar! We'll look into this soon.

**Comment by yahavi** [comment]
@manuchandrasekhar 
This issue is already resolved in the latest version v1.1.0. Feel free to upgrade.

**Explanation**
Before 1.1.0, we used @actions/core dependency v1.2.1. As can be seen [here](https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md#126), this issue is resolved in @actions/core v1.2.6. Therefore in setup-jfrog-cli v1.1.0 we upgraded @actions/core to v1.2.6.

We'd appreciate your feedback for that.

By the way, in order to constantly receive our latest non-breaking changes and fixes, you can use the `@v1` tag, for example:
```yaml
- uses: jfrog/setup-jfrog-cli@v1
- run: jfrog --version
```

**Comment by manuchandrasekhar** [comment]
Thank you for the quick response on this.
